### ISSUE TITLE
Repos made private after the fact

### ISSUE THREAD

**Issue by robobenklein** [utk-se/CodeAnalytics-distributor#6]
```
[2020-02-20 04:46:15] [    INFO] [worker checkin] Checkin completed: claimed job
[2020-02-20 04:46:15] [    INFO] [worker main_loop] Claimed job: 5e28c9221342c9331683f819, going to work.
[2020-02-20 04:46:15] [    INFO] [worker checkin] Checkin completed: setup
[2020-02-20 04:46:15] [    INFO] [worker checkin] Checkin completed: clone
[2020-02-20 04:46:15] [    INFO] [worker run_job] Beginning clone for job 5e28c9221342c9331683f819
[2020-02-20 04:46:15] [   ERROR] [worker __main__] Unknown exception: remote authentication required but no callback set
[2020-02-20 04:46:15] [    INFO] [worker checkin] Checkin completed: error
Traceback (most recent call last):
  File "/home/ca-worker/venv/bin/ca-worker", line 8, in <module>
    sys.exit(__main__())
  File "/home/ca-worker/venv/lib/python3.6/site-packages/cadistributor/worker.py", line 257, in __main__
    raise e
  File "/home/ca-worker/venv/lib/python3.6/site-packages/cadistributor/worker.py", line 243, in __main__
    main_loop()
  File "/home/ca-worker/venv/lib/python3.6/site-packages/cadistributor/worker.py", line 271, in main_loop
    run_job(job)
  File "/home/ca-worker/venv/lib/python3.6/site-packages/cadistributor/worker.py", line 121, in run_job
    repodir
  File "/home/ca-worker/venv/lib/python3.6/site-packages/pygit2/__init__.py", line 261, in clone_repository
    check_error(err)
  File "/home/ca-worker/venv/lib/python3.6/site-packages/pygit2/errors.py", line 61, in check_error
    raise GitError(message)
_pygit2.GitError: remote authentication required but no callback set
```

**Comment by robobenklein** [comment]
solved by leaving the error notice in the results
